var mongoose = require("mongoose");
var Business = require("./models/business");

var data = [
  {
    name: "B2 Harlem",
    address: "271 W 119th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "https://www.b2harlem.com",
    category: "Food",
    description: "Billie's Black restaurateur Adriane Ferguson collaborated with HGTV celebrity designer Mikel Welch to launch B2 Harlem; a new seafood concept for the Harlem community. B2 Harlem will give you a downtown upscale casual dining experience right in the heart of Harlem. The menu boast dishes such as Fresh Oysters, Tempura Filled Squash Blossoms, Oyster Chowder and King Crab Squid Ink Pasta.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "Yes",
    meetCriteria: "Yes",
    owner: "Black Women-owned",
    phoneNumber: "(212) 280-2248",
    searchTags: "B2, Harlem, Restaurant, Seafood, Food",
    subCategory: "Restaurant",
    image: "/IMG_2767.jpg"
  },
  {
    name: "Blujeen",
    address: "2143 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.blujeennyc.com",
    category: "Food",
    description: "Here at blujeen we blend traditional soul, southern, and American cooking with new ingredients, a few new techniques and twists, but never straying too far from the ?soul? of the dish.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 256-1073",
    searchTags: "Bluejeen, Soul Food, Soulfood, Southern Food,",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "BLVD Bistro",
    address: "239 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.boulevardbistrony.com",
    category: "Food",
    description: "BLVD is both a family business and personal calling.?Carlos, who started cooking at the age of 6 while growing up in Natchez, Mississippi, focuses on the food, menu and music?a personally curated mix ranging from classic and contemporary R&B, pop and soul artists, to classic gospel and Aretha in all her manifestations- while his wife Markisha focuses on the business aspects of a shared passion for great food served in a warm, welcoming setting.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 678-6200",
    searchTags: "BLVD, Restaurant, Soul Food, Contemporary,",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Devins Fish and Chips",
    address: "747 St Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "",
    category: "Food",
    description: "Renowned Harlem seafood / Fish & Chips restaurant",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 491-5518",
    searchTags: "Devins, Chips, Fish, Seafood",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Famous Fish Market",
    address: "684 St. Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.yelp.com/biz/famous-fish-market-new-york",
    category: "Food",
    description: "Small, popular  fish shack",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 491-8323",
    searchTags: "Famous, Fish, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Harlem Shake 1",
    address: "100 W 124th St",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "www.harlemshakenyc.com",
    category: "Food",
    description: "From our burgers made with custom blend Pat LaFrieda patties, NY-style, all-beef hot dogs, chicken sandwiches and grilled cheese/melts, to our entr?e-size salads, sides and hand-spun shakes featuring Blue Marble Ice Cream, we use only the highest-quality, all-natural ingredients.",
    giveBack: "Yes, Harlem Shake donates to several local charities. Learn more here",
    hireLocal: "Yes. Approx 80% are hired locally",
    meetCriteria: "",
    owner: "Woman-owned",
    phoneNumber: "(212) 222-8300",
    searchTags: "Harlem, Shakes, Burgers",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Harlem Shake 2",
    address: "2162 2nd Ave",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "www.harlemshakenyc.com",
    category: "Food",
    description: "From our burgers made with custom blend Pat LaFrieda patties, NY-style, all-beef hot dogs, chicken sandwiches and grilled cheese/melts, to our entr?e-size salads, sides and hand-spun shakes featuring Blue Marble Ice Cream, we use only the highest-quality, all-natural ingredients.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "Yes. Approx 80% are hired locally",
    meetCriteria: "",
    owner: "Woman-owned",
    phoneNumber: "212-222-8311",
    searchTags: "Harlem, Burgers, Shakes, Restaurant, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Home Sweet Harlem",
    address: "1528 Amsterdam Ave",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "https://www.yelp.com/biz/home-sweet-harlem-new-york",
    category: "Food",
    description: "A cozy American bistro that is that \"Chill Spot\" in Harlem. Please join us for \"Home\" cooking. Catering is available. A lovely Event Space with Live Music.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 926-9616",
    searchTags: "Home, Sweet, Harlem, Restaurant, Food, Catering, Live Music",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Jacobs Soul Food and Salad Bar 1",
    address: "2695 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.jacobrestaurant.com/",
    category: "Food",
    description: "Family-friendly buffet restaurant offering Southern & Caribbean soul food favorites & a salad bar.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 283-3663",
    searchTags: "Jacobs, Soul Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Jacobs Soul Food and SaladBar 2",
    address: "373 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.jacobrestaurant.com/",
    category: "Food",
    description: "Family-friendly buffet restaurant offering Southern & Caribbean soul food favorites & a salad bar.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 866-3663",
    searchTags: "Jacobs, Soul Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Juicy Grill Juice Bar & Restaurant",
    address: "1646 Madison Ave",
    city: "New York,",
    state: "NY",
    zip: 10029,
    website: "https://www.facebook.com/JuicyGrill110th/?ref=page_internal",
    category: "Food",
    description: "Soul food, juice bar & smoothies, Caribbean",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "347-0507-6866",
    searchTags: "Juicy, Grill, Soul food, juice bar, smoothies, Caribbean",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Lido",
    address: "2168 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "www.lidoharlem.com",
    category: "Food",
    description: "Lido is perfectly positioned on a busy corner on Harlem?s Restaurant Row. Inside there is seating for up to 70, with green leather banquettes, and a large sociable bar.There are daily specials, so customers who come three times a week ? and many do ? always have something new to discover.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Woman-owned",
    phoneNumber: "(646) 490-8575",
    searchTags: "LidoRestaurant",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "LoLo's Seafood Shack",
    address: "303 W 116th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.lolosseafoodshack.com",
    category: "Food",
    description: "Your next island getaway just got a lot closer!  Executive Chef Raymond Mohan and Restaurateur  Leticia Young opened LoLo?s Seafood Shack in the Winter of 2014.  LoLo's Seafood Shack serves up a variety of seafood from the coastal comfort foods of the Cape like sauced shrimp to Caribbean street eats like our crunchy conch fritters.  LoLo's is a NY Times Critic pick that has been featured on ABC, CBS, NBC, Eater, Potluck Video, The Infatuation, NY Post, NY Daily News, NY Magazine, Nation's Restaurant News, Refinery 29, Food & Wine, Village Voice and Zagat among others. . For more information about LoLo?s and it?s upcoming bar opening please contact LoLo?s creator and co-owner, Leticia Skai Young at 646. 649.3356 or Leticia@lolosseafoodshack.com",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(929) 256-2509",
    searchTags: "Lolo's, shack, Food, Restaurant, bar, seafood, caribbean",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Londel's Restaurant",
    address: "2620 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.londelsrestaurant.com",
    category: "Food",
    description: "The restaurant?s slogan, ?Redefining the Harlem Dining Experience,? captures the spirit of the ?new? Harlem.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 234-6114",
    searchTags: "Londel's, Restaurant, Food, Soulfood, Soul food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Maison Harlem",
    address: "341 Saint Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.maisonharlem.com",
    category: "Food",
    description: "Maison Harlem is pleased to be the newest culinary destination spot to join West Harlem's vibrant community.  Featuring a charming rustic interior that perfectly compliments the mouth-watering French Bistro style menu and superb wine selection",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 222-9224",
    searchTags: "Maison, Harlem, Restaurant, French, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Masawa",
    address: "1239 Amsterdam Ave",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.massawanyc.com/",
    category: "Food",
    description: "Opened in 1988, Massawa serves traditional Ethiopian and Eritrean dishes.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 663-0505",
    searchTags: "Masawa, Restaurant, Food, Ethiopian, Eritrean",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Melba's",
    address: "300 W 114th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.melbasrestaurant.com",
    category: "Food",
    description: "Southern classics served in a retro setting that's relaxed & homey by day, bustling in the evening.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 864-7777",
    searchTags: "Melba's, Restaurant, Soulfood, Soul food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Nabe Harlem",
    address: "2367 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.nabeunderground.com",
    category: "Food",
    description: "NABE, Japanese Hotpot, is an interactive eating experience where broth, vegetables, meat and variety of ingredients are cooked in a ceramic hotpot centered between guests who cook and eat together. NABE, always a unique bonding experience, fostering togetherness and stimulating conversation, along with the rest of the menu, reintroduces Japanese Cuisine as something other than Sushi and Ramen. The owner, upon coming home after living 7 years in Japan, thought it would definitely be something Harlem would appreciate and enjoy.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 370-4008",
    searchTags: "Nabe, Harlem, Restaurant, Japanese Food, Hotpot, hot pot",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "New Harlem Besame Restaurant",
    address: "2070 Adam Clayton Powell Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.harlembesame.com",
    category: "Food",
    description: "Bustling family-owned eatery featuring traditional Latin meals & cocktails in a lively atmosphere.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 863-2277",
    searchTags: "New, Harlem, Restaurant, Lounge, Drinks, Cocktails, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Red Rooster",
    address: "310 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.redroosterharlem.com",
    category: "Food",
    description: "Popular, stylish comfort food eatery with creative cooking from celeb chef Marcus Samuelsson.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 792-9001",
    searchTags: "Red, Rooster, Restaurant, Drinks, Cocktails, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Safari Restaurant",
    address: "215 West 116 St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.safariharlem.net",
    category: "Food",
    description: "This is the only Somali restaurant in New York City. Safari specializes in authentic gourmet Somali food, tea & hot sauces.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 964-4252",
    searchTags: "Safari, Somali, Restaurant, Food, Tea",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Savann",
    address: "2280 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.savannrestaurant.com/",
    category: "Food",
    description: "Contemporary Mediterranean bar & eatery presenting refined Turkish dishes in an intimate atmosphere.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Woman-owned",
    phoneNumber: "(212) 222-7990",
    searchTags: "Savann, Restaurant",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Sylvia's Restaurant",
    address: "328 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.sylviasrestaurant.com",
    category: "Food",
    description: "Harlem landmark serving generous helpings of Southern comfort food since 1962.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 996-0660",
    searchTags: "Sylvia's, Restaurant, Soulfood, Soul food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Season Vegan",
    address: "55 Saint Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.seasonedvegan.com",
    category: "Food",
    description: "This counter-serve offers vegan dishes from organic ingredients prepared with global flavors.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 222-0092",
    searchTags: "Season, Restaurant, Vegan, Food, Cafe",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Streetbird Rotisserie",
    address: "2149 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.streetbirdnyc.com",
    category: "Food",
    description: "Marcus Samuelsson?s chicken joint for roasted birds, noodles, sides & cocktails in funky digs.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 206-2557",
    searchTags: "Streetbird, Rotisserie, Restaurant, Bar, Cocktails, Drinks, Chicken, Noodles",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Settepani",
    address: "196 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.settepani.com",
    category: "Food",
    description: "Stylish, relaxed Italian neighborhood cafe in Lower Harlem known for its desserts.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(917) 492-4806",
    searchTags: "Settepani, Italian, Dessert",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Taste of Seafood",
    address: "2530 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10037,
    website: "http://www.atasteofseafood.com/",
    category: "Food",
    description: "A Taste of Seafood was established in 1993 as a Mom and Pop, offering only fried fish and fries on Harlem's famous 125th street",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 796-0275",
    searchTags: "Taste, of, Seafood, Restaurant",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "The Edge",
    address: "101 Edgecombe Ave",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.edgecafeharlem.com",
    category: "Food",
    description: "We are a local eatery in the heart of Hamilton Heights, Harlem. Casual cuisine. Flavors of Jamaica and England with a little New York attitude.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 939-9688",
    searchTags: "The, Edge, Restaurant, Jamaican, English, Food, cafe",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Tsion Cafe & Bakery",
    address: "763 Saint Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "http://www.tsioncafe.com",
    category: "Food",
    description: "Petite, stylish cafe featuring contemporary Ethiopian cuisine in a warm space with patio seating.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 234-2070",
    searchTags: "Tsion, Cafe, Food, Ethiopian, bakery",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Vinateria",
    address: "2211 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.vinaterianyc.com/menu/",
    category: "Food",
    description: "Chic, contemporary spot pairing wine & cocktails with upscale Italian- & Spanish-influenced cooking.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Woman-owned",
    phoneNumber: "212-662-8462",
    searchTags: "Vinateria, Restaurant",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Yatenga French Bistro & Bar",
    address: "2269 Adam Clayton Powell Jr Blvd #1",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.yatengabistro.com",
    category: "Food",
    description: "Stylish, casual eatery featuring ? la carte & fixed-price menus of traditional French bistro fare.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 690-0699",
    searchTags: "Yatenga, Bistro, Bar, Restaurant, French, Food",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "Zoma",
    address: "2084 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.zomanyc.com/",
    category: "Food",
    description: "Modern, upscale Lower Harlem setting for Ethiopian cuisine, including stews eaten with injera bread.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 662-0620",
    searchTags: "Zoma, Food, Ethiopian, Restaurant",
    subCategory: "Restaurant",
    image: ""
  },
  {
    name: "67 Orange",
    address: "2082 Frederick Douglas Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.67orangestreet.com",
    category: "Food",
    description: "Bi-level Harlem lounge with a cozy vintage-speakeasy feel serving cocktails & small plates.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 662-2030",
    searchTags: "67, Orange, Restaurant, Bar, Drinks, Cocktails, Drinks, Food",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Angel of Harlem",
    address: "2272 Frederick Douglass Boulevard",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.angelofharlemnyc.com/",
    category: "Food",
    description: "Angel of Harlem is located in the heart of Harlem's New Restaurant row. We opened our doors in July 2015 and serve Contemporary American cuisine with Latin & Caribbean flavors. Our food and cocktail menus offer authentic specialties prepared with local, fresh ingredients.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Women-owned",
    phoneNumber: "212-316-0350",
    searchTags: "Angel, of, Harlem, Bar, Food, Beer",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Chocolat Restaurant Lounge",
    address: "2223 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.chocolatharlem.com",
    category: "Food",
    description: "Chocolat Restaurant and Lounge creates a one-of-a-kind experience that allows its visitors to enter an urban and sophisticated world that pleasures the palate.  Whether it?s an intimate evening for two or happy hour at the bar, dinner with colleagues or a family gathering for brunch, catching up with the girls or watching the game with the fellas; Chocolat has the ambiance to fit every occasion.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 222-4545",
    searchTags: "Chocolat, Restaurant, Bar, Lounge, Cocktails, Happy Hour, Food",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Corner Social",
    address: "321 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.cornersocialnyc.com/",
    category: "Food",
    description: "Harlem restaurant/bar with upscale pub menu, craft beers, outdoor seating & special DJ nights.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Hispanic woman-owned",
    phoneNumber: "212-510-8552",
    searchTags: "Corner, Social, Food, beer, drinks, music",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Cove Lounge",
    address: "325 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.covelounge.com",
    category: "Food",
    description: "The Cove Lounge is a Caribbean inspired restaurant and lounge in Harlem. Attracting an array of business professionals, entrepreneurs, and celebrities.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 665-3455",
    searchTags: "Cove, Restaurant, Bar, Lounge, Cocktails, Caribbean, Food",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Ginny's Supper Club",
    address: "310 Lenox Ave",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.ginnyssupperclub.com/",
    category: "Food",
    description: "Impeccably designed by co-owner Andrew Chapman, our classic Harlem speakeasy vibe lends itself perfectly to creating memorable days and nights of celebration featuring the legendary music of Harlem and Chef Marcus Samuelsson?s world renowned cuisine.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "212.421.3821",
    searchTags: "Ginny's, Supper, Drinks, Cocktails,  Dancing, Club, Speakeasy",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Harlem Brewery",
    address: "360 W 125th St",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "www.harlembrewing.com/",
    category: "Food",
    description: "Harlem Brewing manufactures craft beverages. Its flagship Sugar Hill Golden Ale and Harlem Renaissance Wit both celebrate the rich history of Harlem. The company was founded in 2000 and is based in Harlem, USA.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "Yes",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(888) 876-2420",
    searchTags: "Harlem, Brewery, Bar, Food, Beer",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Hop House",
    address: "2224 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "https://www.hophouseharlem.com/",
    category: "Food",
    description: "Taproom & Kitchen serving New York's best local craft brews. The menu offers plenty of bites to pair with the slate of hop centered beers.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Women Owned",
    phoneNumber: "(646) 858-0252",
    searchTags: "Hop, House, Restaurant, Bar, Craft, Beer",
    subCategory: "Restaurant/Nightlife",
    image: ""
  },
  {
    name: "Hyacinth's Haven",
    address: "2374 Adam Clayton Powell Jr Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.hyacinthshaven.com/",
    category: "Food",
    description: "Located in the Historic Striver?s Row section of Harlem. Hyacinth?s Haven is a classic cocktail bar, restaurant that offers a retreat from your hectic day. Step in and you will be welcomed by one of our friendly staff. Join us in the back Patio during the warm months as you retreat to the peace and quiet of New York City.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 755-8161",
    searchTags: "Hyacinth's, Haven, Restaurant, Bar, Cocktails, Drinks, Food, Jamaican, Reggae",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Lenox Saphire Bar & Restaurant",
    address: "341 Lenox Ave",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.lenoxsaphireharlem.com/",
    category: "Food",
    description: "Lenox Saphire brings forth a fusion of Senegalese cuisine and American soul food. Known for our rich culture, we proudly serve freshly made French pastries and breads daily.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 866-9700",
    searchTags: "Lenox, Saphire, Bar, Nightlife, Restaurant",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Minton's",
    address: "206 W 118th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.mintonsharlem.com",
    category: "Food",
    description: "Welcome to Minton's. A Harlem Legend reborn. Minton's is a revival of one of New York City's most famous music venues",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 243-2222",
    searchTags: "Minton's, Restaurant, Bar, Cocktails, Drinks, Food, Music",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "MIST Harlem",
    address: "46 W 116th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://mistharlem.com/",
    category: "Food",
    description: "Modern bar & casual cafe with a menu of modern takes on American classics & occasional live music.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 828-6478",
    searchTags: "Mist, Harlem, Bar, Cafe, Restaurant, Music",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Moca Lounge",
    address: "2210 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "https://www.facebook.com/mocalounge/",
    category: "Food",
    description: "Indulge yourself in this beautiful lounge that boasts of exotic art, comfortable seating and seductive lighting. Moca has a stylish reputation for it's smooth music, sensual and sexy feel. Great service, food and drinks are normal fare.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 665-8081",
    searchTags: "Moca, Restaurant, Bar, Nightlight, Cocktails, Lounge, Music",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Solomon & Kuff",
    address: "2331 12th Ave",
    city: "New York",
    state: "NY",
    zip: 10027,
    website: "http://www.solomonandkuff.com",
    category: "Food",
    description: "Sizable restaurant & bar for Caribbean dishes, a huge rum selection & DJ nights.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 939-9443",
    searchTags: "Solomon, &, and, Kuff, Restaurant, Bar, Cocktails, Drinks, Caribbean, Rum, DJ",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Studio 735 Bar& Grill Lounge",
    address: "735 Saint Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "",
    category: "Food",
    description: "Bar & Grill Lounge",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(917) 326-1138",
    searchTags: "Studio, 735, Bar, Grill, Nightlife, Club, Cocktails, Drinks",
    subCategory: "Bar/Nightlife",
    image: ""
  },
  {
    name: "Branson's Got Juice",
    address: "741 St. Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "http://www.bransongotjuice.com/",
    category: "Food",
    description: "Our mission at ?Branson Got Juice? is to provide our guests with a superior selection of health oriented beverages and foods.  This is done by carefully selecting top of the line ingredients, ensuring delicious recipes that will amaze your senses. We aim to educate our patrons on the beneficial qualities of the various items we offer while maintaining an exceptional standard of customer service.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "Yes",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "212-283-2700",
    searchTags: "Branson's, Got, Health, Juice, Smoothies",
    subCategory: "Cafe",
    image: ""
  },
  {
    name: "Patisserie Des Ambassades",
    address: "2200 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.patisseriedesambassades.com",
    category: "Food",
    description: "Storefront cafe featuring classic French pastries & Senegalese fare in a basic environment (BYOB).",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 666-0078",
    searchTags: "Patisserie, Des, Ambassades, Food, Senegalese, French, BYOB, Pastries",
    subCategory: "Cafe",
    image: ""
  },
  {
    name: "Reggae Sun Delight and Juice Bar",
    address: "234 West 145th St",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "",
    category: "Food",
    description: "Neighborhood smoothie and health foods store",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(347) 472-6265",
    searchTags: "Reggae, Sun, Delight, and, Juice, Bar, Cafe, Healthy, Smoothie",
    subCategory: "Cafe",
    image: ""
  },
  {
    name: "Serengeti Teas & Spices",
    address: "2292 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.serengetiteasandspices.com",
    category: "Food",
    description: "",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 866-7100",
    searchTags: "Serengeti, Spices, Cafe, Tea",
    subCategory: "Cafe",
    image: ""
  },
  {
    name: "Lady Lexis Sweets",
    address: "1931 Madison Ave",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.ladylexissweets.com/",
    category: "Food",
    description: "We have all of your favorites Nutty Nut Brittle, Rugelachs, Sweet Potato Loaf, Carrot Cake, Peanut butter oatmeal cookies and much more! So come out to our pop up shop on the corner of 124th and Madison and try our sweets. We are sure you will be sweetly satisfied.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 534-0330",
    searchTags: "Lady, Lexis, Baked goods, sweets, cookies, cake",
    subCategory: "Bakery",
    image: ""
  },
  {
    name: "Lee Lee's Baked Goods",
    address: "283 W 118th St",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.leeleesrugelach.com",
    category: "Food",
    description: "Alvin Lee Smalls (known affectionately in the Village of Harlem as Lee-Lee or Mr. Lee) has a passion for baking better-than-store bought goodies; his Rugelach are made from only the best all natural ingredients. He?s put his own twist on tradition to bring you his critically acclaimed Rugelach. One taste will transport you to a world of true indulgence. Let our time-honored tradition become yours!",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(917) 493-6633",
    searchTags: "Lee's, Baked, Goods, Bakery, Cake, Cookies, Sweets",
    subCategory: "Bakery",
    image: ""
  },
  {
    name: "Make My Cake 1",
    address: "121 Saint Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.makemycake.com",
    category: "Food",
    description: "Evolving from a home-based business, over 15 years ago, that only sold holiday cakes, we were compelled to address our customer demand by expanding the business to several full service retail and wholesale bakeries. Our family has managed to set the baking world on fire growing Make My Cake into a global sensation which draws thousands of worldwide visitors seeking the ultimate \"red velvet cake\" and various other heavenly desserts to Harlem. At Make My Cake, we serve our sweet creations like Food Network favorite - German Chocolate Cake, New York Times pick - Red Velvet Cake, and local favorite - Sweet Potato Cheesecake to the fans which flock to our bakeries daily.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 932-0833",
    searchTags: "Make, My, Bakery, Cake, Cookies, Sweets",
    subCategory: "Bakery",
    image: ""
  },
  {
    name: "Make My Cake 2",
    address: "2380 Adam Clayton Powell Jr Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.makemycake.com",
    category: "Food",
    description: "Evolving from a home-based business, over 15 years ago, that only sold holiday cakes, we were compelled to address our customer demand by expanding the business to several full service retail and wholesale bakeries. Our family has managed to set the baking world on fire growing Make My Cake into a global sensation which draws thousands of worldwide visitors seeking the ultimate \"red velvet cake\" and various other heavenly desserts to Harlem. At Make My Cake, we serve our sweet creations like Food Network favorite - German Chocolate Cake, New York Times pick - Red Velvet Cake, and local favorite - Sweet Potato Cheesecake to the fans which flock to our bakeries daily.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 234-2344",
    searchTags: "Make, My, Bakery, Cake, Cookies, Sweets",
    subCategory: "Bakery",
    image: ""
  },
  {
    name: "Harlem Chocolate Factory",
    address: "2363 Adam Clayton Powell Jr. Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.harlemchocolatefactory.com/",
    category: "Food",
    description: "The Harlem Chocolate Factory is an artisan chocolate company based in Harlem. We are handcrafting chocolates and confections in Harlem using high-quality and responsibly sourced ingredients.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "info@harlemchocolatefactory.com",
    searchTags: "Harlem, Chocolate, Factory, Bakery, Cake, Cookies, Sweets",
    subCategory: "Bakery",
    image: ""
  },
  {
    name: "Fortitude's Son",
    address: "135 West 123rd street",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "",
    category: "Food",
    description: "Custom Catered Meals & Custom Tailored Art",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(347 )469-9107",
    searchTags: "Fortitude's, Son, Food, Catering, Art",
    subCategory: "Catering",
    image: ""
  },
  {
    name: "Gordon's Caribbean Catering",
    address: "216 East 122nd Street",
    city: "New York,",
    state: "NY",
    zip: 10035,
    website: "http://www.beforedessert.com",
    category: "Food",
    description: "A full service catering & personal chef services. Our service provides corporate & commercial catering as well as in home food/meal preparation (healthy eating options) for individual families.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(917) 225-2865",
    searchTags: "Gordon's, Caribbean, Catering, Meal Prep, Personal Chef",
    subCategory: "Catering",
    image: ""
  },
  {
    name: "Now What? Mardi Gras! Inc.",
    address: "2160 Madison Ave",
    city: "New York,",
    state: "NY",
    zip: 10037,
    website: "",
    category: "Food",
    description: "Small catering services and private chef work. The business will eventually be a full service restaurant.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 694-2234",
    searchTags: "Now, What, Mardi, Gras, Catering, Private Chef",
    subCategory: "Catering",
    image: ""
  },
  {
    name: "Keys to Abundant Life, Inc.",
    address: "70 Park Terrace East",
    city: "New York,",
    state: "NY",
    zip: 10034,
    website: "http://www.keystoabundantlife.com",
    category: "Food",
    description: "We conduct hands on healthy cooking classes for children and adults. We conduct healthy living and nutrition workshops as well or personal",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 319-6979",
    searchTags: "Keys, to, Abundant, Life, Cooking, Classes, Nutrition, Workshops",
    subCategory: "Classes",
    image: ""
  },
  {
    name: "BebeNoir",
    address: "2064 Adam Clayton Powell Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.bebenoir.com",
    category: "Shopping",
    description: "BebeNoir is a New York based clothing company founded by Ibrahima Doukoure. Originally from Guinea, West, Ibrahima spent most of this childhood in Senegal and Italy. The idea of Beb?noir emerged in early 2004 over dinner with close friends at an African restaurant in Harlem, New York.",
    giveBack: "Yes. Beb?Noir offers an internship program for high-school students and sponsors events at a elementary local school",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "(212) 828-5775 _ ?",
    searchTags: "BebeNoir, Africa, Clothing, Boutique",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Calabar Imports",
    address: "2504 Frederick Douglass Blvd.",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "www.calabar-imports.com",
    category: "Shopping",
    description: "Calabar Imports is a retail store with imported products. The store and business is owned by Heloise Annette Oton and her daughter, Atim Annette Oton.  We offer stylish, eclectic and affordable fashion clothing, fashion accessories, jewelry, home decor and gifts to consumers wanting to create a unique personalized home environment and accessorize their body.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 964-5062",
    searchTags: "Calabar, Imports, Clothing, Clothes, Imported, Jewelry, Accessories",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Harlem Boutique",
    address: "422 Malcolm X Blvd A",
    city: "New York,",
    state: "NY",
    zip: 10037,
    website: "NA",
    category: "Shopping",
    description: "Small boutique",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 368-1980",
    searchTags: "Harlem, Clothing, Boutique",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Harlem Haberdashery",
    address: "245 Lenox Ave.",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "https://www.harlemhaberdashery.com/",
    category: "Shopping",
    description: "HARLEM HABERDASHERY is the retail expression of 5001 FLAVORS, a custom-made apparel company creating looks for celebrities, recording artists and sports stars for over 20 years.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 707-0070_",
    searchTags: "Harlem, Clothing, Clothes, Shop, Dress, Haberdashery",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Harlem Underground",
    address: "2219 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.harlemunderground.com/",
    category: "Shopping",
    description: "Harlem Underground opened its doors in 1998. From the onset HU has embodied the essence of Harlem, New York City, the epicenter of African-American culture. Harlem Underground has two locations. We provide quality and unique apparel that transcends time.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "212-987-9385",
    searchTags: "Harlem, Underground, Clothing, Clothes, Shop, Dress",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Harlem Underground 2",
    address: "20 E 125th St",
    city: "New York,",
    state: "NY",
    zip: 10035,
    website: "www.harlemunderground.com/",
    category: "Shopping",
    description: "Harlem Underground opened its doors in 1998. From the onset HU has embodied the essence of Harlem, New York City, the epicenter of African-American culture. Harlem Underground has two locations. We provide quality and unique apparel that transcends time.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "212-987-9385",
    searchTags: "Harlem, Underground, Clothing, Clothes, Shop, Dress",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Neighborhood Women's Collective Thrift & Vintage Store",
    address: "2494 Frederick Douglass Blvd.",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.neighborhoodwomenscollective.org/",
    category: "Shopping",
    description: "The Neighborhood Women?s Collective Inc. is dedicated to encouraging women and girls to be active members of their communities and confident of their own powers to identify and resolve important issues in their lives. The space is paid for in part by selling clothes and other items",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(914) 257-3635",
    searchTags: "Neighborhood, Women's, Collective, Thift, Vintage, Clothing, community, shopping",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Flamekeepers Hat Club",
    address: "273 West 121st Street",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.flamekeepershatclub.com/",
    category: "Shopping",
    description: "Custom Hats for Stylish Men and Women",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 531-3542",
    searchTags: "Flamekeepers, Club, Hats, Clothes, Shopping, Custom",
    subCategory: "Clothing",
    image: ""
  },
  {
    name: "Harlem Soap",
    address: "Online",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://harlemsoap.bigcartel.com/",
    category: "Shopping",
    description: "Harlem-based soap company",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black owned",
    phoneNumber: "NA",
    searchTags: "Harlem, Soap, Handmade, Natural",
    subCategory: "Gifts",
    image: ""
  },
  {
    name: "NiLu",
    address: "191 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://shopnilu.com/",
    category: "Shopping",
    description: "Local gift shop",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(646) 964-4926",
    searchTags: "NiLu, Gifts, handmade",
    subCategory: "Gifts",
    image: ""
  },
  {
    name: "Salud Para Todos",
    address: "4791 Broadway",
    city: "New York,",
    state: "NY",
    zip: 10034,
    website: "http://www.salud.bz",
    category: "Shopping",
    description: "Sale and manufacturing of all natural nutritional supplements, vitamins, snacks, skincare, beauty products including proprietary blends of plants and herbs.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Hispanic-owned",
    phoneNumber: "(718) 568-9997",
    searchTags: "Salud, Para, Todos, Supplements, Vitamins, Health, Supplements",
    subCategory: "Health",
    image: ""
  },
  {
    name: "Seven Grain",
    address: "2322 Adam Clayton Powell Jr Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "NA",
    category: "Shopping",
    description: "Health foods store",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 862-3760",
    searchTags: "Seven, Grain, Supplements, Vitamins, Health, Supplements",
    subCategory: "Health",
    image: ""
  },
  {
    name: "BTL Liquor",
    address: "311 West 127th",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://btlharlem.com/",
    category: "Shopping",
    description: "At BTL Harlem, discover a world of wine--literally! We specialize in acquiring rare production releases from all across North America, South America, Africa, Europe and Asia",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 222-1099",
    searchTags: "BTL, Liquor, Wine, Alcohol, Store",
    subCategory: "Alcohol",
    image: ""
  },
  {
    name: "Pompette Wines and Spirits",
    address: "420 Lenox Ave",
    city: "New York,",
    state: "NY",
    zip: 10037,
    website: "http://www.pompettewines.com/",
    category: "Shopping",
    description: "Locally-owned wine store with a wide variety of international wines",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 368-9463",
    searchTags: "Pompette, Spirits, Wine, Alcohol, Liquor, Store",
    subCategory: "Alcohol",
    image: ""
  },
  {
    name: "Roy Wine and Liquors",
    address: "2618 Fredrick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "https://www.yelp.com/biz/roy-wine-and-liquors-new-york",
    category: "Shopping",
    description: "Discount liquor store",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 694-0550",
    searchTags: "Roy, Wine, Liquor, Alcohol, Liquor Store,",
    subCategory: "Alcohol",
    image: ""
  },
  {
    name: "Sisters Uptown Bookstore",
    address: "1942 Amsterdam Ave",
    city: "New York,",
    state: "NY",
    zip: 10032,
    website: "http://www.sistersuptownbookstore.com/",
    category: "Shopping",
    description: "We are not just a book store; we are a community resource center for the exchange of information and ideas. Our motto is ?Knowledge of Self is the key to Understanding?. We provide an educational, emotional, spiritual and loving environment for a diverse community, where all are welcome.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 862-3680",
    searchTags: "Sisters, Uptown, Books, Resources",
    subCategory: "Books",
    image: ""
  },
  {
    name: "Black Ink",
    address: "50 W 125th St",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.blackink.nyc/",
    category: "Cultural",
    description: "Our mission at Black Ink Tattoo Studio is to always be innovative in our tattoo design and techniques.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 360-4512",
    searchTags: "Black, Tattoo, Ink, Art",
    subCategory: "Art",
    image: ""
  },
  {
    name: "Casa Frela",
    address: "47 West 119th Street",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.casafrela.com",
    category: "Cultural",
    description: "Casa Frela Gallery is a community focused art gallery created to inspire explore and promote to partner the business of art and the life of commerce by uniting businesses artist and residents and progressive way to cultivate art interest aware and education",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Hispanic-owned",
    phoneNumber: "(212) 722-8577",
    searchTags: "Casa Frela, Community, Art, Education, Gallery",
    subCategory: "Art",
    image: ""
  },
  {
    name: "ImageNation Cinema",
    address: "2031 Adam Clayton Powell Jr. Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.imagenation.us/",
    category: "Cultural",
    description: "ImageNation Cinema Foundation is a Harlem-based media arts group, founded with the goal of establishing a chain of art-house cinemas, dedicated to progressive media by and about people of color. Through a variety of exhibitions and programs, ImageNation edifies its audience. We foster media equity, media literacy, solidarity, cross-cultural exchange and highlight the humanity of Pan-African people worldwide.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "",
    searchTags: "Image, Nation, ImageNation, Culture, media, Foundation, Arts, Cinema, Literacy, Equity, Solidarity",
    subCategory: "Art",
    image: ""
  },
  {
    name: "La Maison D'Arte Gallery",
    address: "259 west 132nd street",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.lamaisondartny.com/",
    category: "Cultural",
    description: "La Maison d'Art is a unique Private Art Gallery set up to accommodate not just a particular medium, but to unite artists from a variety of backgrounds: visual, spoken word, dance, film, etc. aimed to provoke discussions, debates and critique about the role of art in society.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Woman-owned",
    phoneNumber: "718)593-4108 / (917-)533-4605",
    searchTags: "La Maison, D'arte, Art, Gallery, Museum",
    subCategory: "Art",
    image: ""
  },
  {
    name: "Harlem School of the Arts",
    address: "645 Saint Nicholas Avenue",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "https://hsanyc.org/",
    category: "Cultural",
    description: "Harlem School of the Arts is committed to leveling the playing field by empowering young people from across the multi-cultural and socio-economic spectrum. Of the nearly 4,000 students who participate in our programs, more than 85% are African American or Latino and nearly 50% of students taking classes at our facility receive financial aid or scholarships, or take advantage of the flexibility of extended payment plans.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "",
    phoneNumber: "(212) 926-4100",
    searchTags: "Harlem, School, of, the, Arts, theatre, music",
    subCategory: "Art",
    image: ""
  },
  {
    name: "The Long Gallery",
    address: "2073 Adam Clayton Powell, Jr Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.long.gallery/exhibitions",
    category: "Cultural",
    description: "Art Gallery in Harlem. Previous exhibitions include topics such as the Million Man March, Civil Rights Movement and Afrofuturism",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646)-559-8368",
    searchTags: "The, Long, Arts, Gallery",
    subCategory: "Art",
    image: ""
  },
  {
    name: "Modu Print",
    address: "2542 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "https://www.thenyax.com/",
    category: "Cultural",
    description: "Modu Printing provides high-quality printing for posters, art, etc.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(347) 577-7710",
    searchTags: "Modu, Prints, Art, Printing, Gallery",
    subCategory: "Art",
    image: ""
  },
  {
    name: "National Black Theatre",
    address: "2031 5th Ave",
    city: "New York,",
    state: "NY",
    zip: 10035,
    website: "www.nationalblacktheatre.org/",
    category: "Cultural",
    description: "Established performance venue showcasing African American plays & events, plus drama education.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "212-722-3800",
    searchTags: "National Black Music, theatre",
    subCategory: "Art",
    image: ""
  },
  {
    name: "Word Art by ShalomIsrael",
    address: "260 Convent Avenue",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "http://www.wordartbyshalomisrael.com",
    category: "Cultural",
    description: "Word Art by ShalomIsrael provides art and education products and workshops for the general public and youth organizations and schools.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(646) 331-9785",
    searchTags: "Word, Art, by, Shalom Israel, Workshops, Art, education",
    subCategory: "Art",
    image: ""
  },
  {
    name: "A Taste of Harlem",
    address: "363 Lenox Avenue",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.tasteharlem.com",
    category: "Cultural",
    description: "A full service sightseeing company specializing in Harlem. Our historical tours allow visitors to eat their way through the neighborhood as they are introduced to Harlem by way of its food, art and music.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black women-owned",
    phoneNumber: "(212) 866-7427",
    searchTags: "A, Taste, of, Harlem, Sightseeing, tours, food, art, music, tourist",
    subCategory: "Art",
    image: ""
  },
  {
    name: "Harlem Heritage",
    address: "104 Malcolm X Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.harlemheritage.com/",
    category: "Cultural",
    description: "Harlem tours conducted by Harlem Heritage Tours by born & raised Harlem residents, offering most authentic Harlem sightseeing experiences and tours.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "212-280-7888",
    searchTags: "Harlem, Heritage, Tours, Sightseeing",
    subCategory: "Tours",
    image: ""
  },
  {
    name: "Harlem Hip Hop Tours",
    address: "69 West 106th Street",
    city: "New York,",
    state: "NY",
    zip: 10025,
    website: "http://h3tours.com",
    category: "Cultural",
    description: "Harlem Hip-Hop Tours field trips and activities relating to Harlem and New York City's Hip-Hop industry to schools and tourist groups from around the world.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 769-9047",
    searchTags: "Harlem, Hip, Hop, Rap, Music, Tours, tourist",
    subCategory: "Tours",
    image: ""
  },
  {
    name: "Harlem, Your Way! Tours Unlimited, Inc.",
    address: "129 West 130th Street",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.harlemyourwaytoursunlimited.com/",
    category: "Cultural",
    description: "We plan and conduct exciting, themed, interactive tours of New York City with adult, student and seniro friendly tour guides who visit historic districs where they explore landmarks, attractions, museums, churches and more. We ofer gospel, jazz and hip hop tours as well as study programs. Participants of the study programs recieve certificates at the end of the session. Tour goeers will enjoy delicious meals at local ethnic restaurants which enhance the cultural experience.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 690-1687",
    searchTags: "Harlem, Your, Way, Sightseeing, tours, food, art, music, tourist",
    subCategory: "Tours",
    image: ""
  },
  {
    name: "Unique NY Tours",
    address: "461 Central Park West",
    city: "New York,",
    state: "NY",
    zip: 10025,
    website: "http://www.unique-tours.com",
    category: "Cultural",
    description: "Unique NY Tours provides private, individualized, guided tours for sightseeing shopping, photography, relocating. We have standard and one-of-a-kind itineraries. We offer tours as engaging team building challenges, and tours aiding teachers in fulfilling NYC DOE teaching standards. Our 2-hour downtown scavenger hunt is open to the public.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 865-7417",
    searchTags: "Unique, NY, Sightseeing, tours, food, art, music, tourist",
    subCategory: "",
    image: ""
  },
  {
    name: "Welcome to Harlem, Inc.",
    address: "2360 Fredrick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.welcometoharlem.com",
    category: "Cultural",
    description: "Welcome To Harlem is the premier visitor center and tour company in Harlem, we pride ourselves on assisting visitors, local and from abroad, who are looking for the off-the-beaten-path sights and sounds of NYC, as well as Harlem. We provide gospel and brunch, walking, and custom tours in Harlem.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(212) 662-7779",
    searchTags: "Welcome, to, Harlem, Sightseeing, tours, food, art, music, tourist",
    subCategory: "Tours",
    image: ""
  },
  {
    name: "Bill's Place",
    address: "148 W 133rd St",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.billsplaceharlem.com/",
    category: "Cultural",
    description: "Jazz legends play the small no-frills room & you can bring your own alcohol. Reservations needed.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 281-0777",
    searchTags: "Bill's, Place, Music",
    subCategory: "Music",
    image: ""
  },
  {
    name: "Mama's Foundation",
    address: "149 W 126th St",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.mamafoundation.org/",
    category: "Cultural",
    description: "Housed in a renovated, attractive, spacious, five story brownstone on 126 Street across from the State Office Building, in Central Harlem, The Mama Foundation is in the heart of the community and in touch with the pulse of the people. The talent and desire are there, waiting to be tapped. Featuring Vy Higginsen's Gospel Choir of Harlem, Uptown Musical Theater Productions, and the award-winning arts education program Gospel for Teens.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 280-1045",
    searchTags: "Mama's, Foundation, Music",
    subCategory: "Music",
    image: ""
  },
  {
    name: "Paris Blues",
    address: "2021 Adam Clayton Powell Junior Blvd",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://parisbluesharlem.webs.com/",
    category: "Cultural",
    description: "Old-school blues bar",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(917) 257-7831",
    searchTags: "Paris, Blues, Music, Jazz",
    subCategory: "Music",
    image: ""
  },
  {
    name: "Fierce Spa Nails",
    address: "2246 1st Avenue",
    city: "New York,",
    state: "NY",
    zip: 10029,
    website: "http://fiercespa.com/",
    category: "Beauty",
    description: "A resident of East Harlem herself, owner, Ms. Guadalupe Castro, has succeeded in her desire to ?make East Harlem pretty? with a family-business that serves the community.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Hispanic woman-owned",
    phoneNumber: "(212) 933-1012",
    searchTags: "Fierce, Spa, Nails, Beauty",
    subCategory: "Nail Salon",
    image: ""
  },
  {
    name: "Polished Fingertips",
    address: "2119 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://polished4.vpweb.com/",
    category: "Beauty",
    description: "Upon entering POLISHED, their signature scent will be your first encounter followed with a friendly greeting and help making your color selection. You'll enjoy a selection of aromatherapy treatments created to leave hands and feet gently-scented and soft, like rose petals.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "",
    phoneNumber: "(212) 222-4466",
    searchTags: "Polished, Fingertips, Nails, Beauty, Nail Salon",
    subCategory: "Nail Salon",
    image: ""
  },
  {
    name: "Hairiette of Harlem",
    address: "473 West 143rd Street",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "http://www.hairiette.com",
    category: "Beauty",
    description: "Healthy hair care products and related media.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-woman owned",
    phoneNumber: "(323) 702-2664",
    searchTags: "Hairiette, of, Harlem, Beauty, Products",
    subCategory: "Beauty Products",
    image: ""
  },
  {
    name: "Mented Cosmetics",
    address: "Online only",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "https://www.mentedcosmetics.com/",
    category: "Beauty",
    description: "Offers lipstick, makeup and other beauty items for all shades/hues",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-woman owned",
    phoneNumber: "",
    searchTags: "Mented, Beauty Supply, Beauty, Cosmetics",
    subCategory: "Beauty Products",
    image: ""
  },
  {
    name: "Vivrant Beauty",
    address: "220 St Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.vivrantbeauty.com/",
    category: "Beauty",
    description: "Vivrant Beauty is Harlem?s newest beauty retail experience with a vast selection of skincare, haircare and cosmetic products catering to women of all skin tones, nationalities and hair textures.",
    giveBack: "Yes, learn more here",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(212) 865-0100",
    searchTags: "Vivrant, Beauty Supply, Beauty, Cosmetics",
    subCategory: "Beauty Products",
    image: ""
  },
  {
    name: "Denny Moe's Superstar Barbershop",
    address: "2496 Frederick Douglass Boulevard",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.dennymoe.com/",
    category: "Beauty",
    description: "Barbershop that gives back to the community by hosting annual Cutting for A Cure event, annual back to school and christmas toy drive, and they even have a college scholarship program.",
    giveBack: "Yes, learn more here",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 690-0015",
    searchTags: "Denny, Moe's, Superstar, Barbershop, Haircut, Cut, Shape up",
    subCategory: "Barbershop",
    image: ""
  },
  {
    name: "Harlem Skin & Laser Clinic",
    address: "2119 Frederick Douglass Blvd",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "www.harlemskinclinic.com",
    category: "Beauty",
    description: "Our mission is simple: to make skin beautiful, share the practice of mindful beauty while providing remarkable service ? one guest at a time.",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(917) 309-6607",
    searchTags: "Harlem, Laser, clinic, Skincare, Skin",
    subCategory: "Beauty",
    image: ""
  },
  {
    name: "Harlem Natural Hair Care Salon",
    address: "751 St. Nicholas Ave",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.harlemnaturalhairsalon.com/",
    category: "Beauty",
    description: "At Harlem Natural Hair, we are committed to creating beautiful styles while maintaining the health of your hair.  We use the finest products that are designed for gentle cleansing and grooming. Our highly skilled and seasoned stylists will create a style that complements you.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(212) 694-6593",
    searchTags: "Harlem, Natural, Care, Hair, Beauty",
    subCategory: "Beauty Salon",
    image: ""
  },
  {
    name: "Mia's Bathhouse for Pets",
    address: "247 West 145th Street Frederick Douglass Blvd.",
    city: "New York,",
    state: "NY",
    zip: 10039,
    website: "http://www.miasbathhouse.com/",
    category: "Services",
    description: "Black woman-owned",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Imagine never having to deal with the hassle and mess of washing your dog in the bathtub or kitchen sink and pay a fraction of what it costs to take them to the groomers!  Save time & money by using our professional supplies and spa products, as well as o",
    phoneNumber: "(212) 694-8607",
    searchTags: "Mia's, Bathhouse, for, Pets, Pet Grooming, Animals, Dogs",
    subCategory: "Pets",
    image: ""
  },
  {
    name: "Wanda's Pet Grooming",
    address: "22 Bradhurst Ave",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "https://www.yelp.com/biz/wandas-pet-grooming-new-york-3",
    category: "Services",
    description: "Pet grooming services",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(212) 690-0010",
    searchTags: "Wanda's, Pets, Pet Grooming, Animals, Dogs",
    subCategory: "Pets",
    image: ""
  },
  {
    name: "Harlem Doggie Day Spa",
    address: "734 Saint Nicholas Ave.",
    city: "New York,",
    state: "NY",
    zip: 10031,
    website: "https://harlemdoggiedayspa.com/",
    category: "Services",
    description: "Doggie day spa and grooming",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "Harlem Doggie Day Spa hires locally and  offers an internship program for youth.",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "(646)524-7936",
    searchTags: "Harlem, Doggie, Day, Spa, Pets, Pet Grooming, Animals, Dogs",
    subCategory: "Pets",
    image: "https://assets.dnainfo.com/photo/2016/12/1482184245-286010/larger.jpg"
  },
  {
    name: "Swim Swim Swim I Say",
    address: "241 West 111th Street",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://www.swimswimswimisay.com",
    category: "Beauty",
    description: "Swim Swim Swim I say is your upper Manhattan home for tots, children, adults, fear of water students, special needs students (including autistic individuals), home pool instruction, pool parties, and stroke correction swimming lessons. We also service the Bronx.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(917) 902-3184",
    searchTags: "Swim, I, Say, Swimming, Gym, Fitness, Physical",
    subCategory: "Fitness",
    image: ""
  },
  {
    name: "La Femme Suite",
    address: "2364 7th Avenue",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://lafemmesuite.com/",
    category: "Beauty",
    description: "Pole dancing classes",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(917)507-9475",
    searchTags: "La, Femme, Suite, Gym, Pole Dancing, Fitness",
    subCategory: "Fitness",
    image: ""
  },
  {
    name: "Cortes Entertainment (Groove Fit)",
    address: "260 West 123rd Street",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "http://www.groovefit.com",
    category: "Beauty",
    description: "Groovefit is a dance and fitness organization that specializes in group classes for all populations: Zumba, Salsa, Total body conditioning, Yoga, Pilates, and dance.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(917) 386-8303",
    searchTags: "Gym, Fitness, Dancing, Classes, Salsa, Zumba, Cortes, Entertainment, Yoga, Pilates",
    subCategory: "Fitness",
    image: ""
  },
  {
    name: "The Fit Lab Harlem",
    address: "226 W 141st Street",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "https://www.facebook.com/The-Fit-Lab-Harlem-123829141293910/",
    category: "Beauty",
    description: "We are a full service personal training studio located in Harlem, NY and our mission is to challenge people to challenge themselves to through exercise.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 386-7440",
    searchTags: "The, Fit, Lab, Harlem, Gym, workout",
    subCategory: "Fitness",
    image: ""
  },
  {
    name: "Harlem Cycle",
    address: "2350 Adam Clayton Powell Blvd",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://harlem-cycle.com/",
    category: "Beauty",
    description: "Indoor cycling and rowing gym",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(646) 404-2891",
    searchTags: "Harlem, Cycle, Gym, Cycling, Rowing, Fitness",
    subCategory: "Fitness",
    image: ""
  },
  {
    name: "Bottom Line Construction",
    address: "104-106 East 126th St., Ste #3B",
    city: "New York,",
    state: "NY",
    zip: 10035,
    website: "https://bottomlineconstructiondevelopment.com/",
    category: "Services",
    description: "Bottom Line Construction Development, LLC (BLCD) is a fully licensed and insured firm with locations in Harlem (East 126th St.) and Queens, NY.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 281-3800",
    searchTags: "Bottom, Line, Construction, Building, Contracting",
    subCategory: "Construction",
    image: ""
  },
  {
    name: "MEGA Personalities",
    address: "",
    city: "New York,",
    state: "NY",
    zip: "",
    website: "http://www.harlem2020.nyc/home.html",
    category: "Services",
    description: "Provides coaching and media services to local businesses",
    giveBack: "Yes. Click here to learn more",
    hireLocal: "",
    meetCriteria: "Yes",
    owner: "Black-owned",
    phoneNumber: "929-841-6541",
    searchTags: "MEGA, Personalities, Misc, Community Development",
    subCategory: "Consulting",
    image: ""
  },
  {
    name: "Hoodwinked",
    address: "151 West 116th Street",
    city: "New York,",
    state: "NY",
    zip: 10026,
    website: "http://hoodwinkedescape.com/",
    category: "Services",
    description: "Harlem's premiere Escape the Room adventure is finally here. Hoodwinked is the perfect activity for date night, fun with friends, family bonding and team building.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "(212) 662-2583",
    searchTags: "Hoodwinked, Adventure, Escape The Room, Mystery, Adventure",
    subCategory: "Entertainment",
    image: ""
  },
  {
    name: "Wright Best Consulting Group",
    address: "WBCG LLC\nPO BOX 1174",
    city: "New York,",
    state: "NY",
    zip: 10027,
    website: "https://www.wrightbest.com/",
    category: "Services",
    description: "Our mission is to provide exceptional organizational effectiveness consulting by focusing on our six key services: leadership development, culture shifting, diversity and inclusion, performance measurement and improvement, budgeting and development, and human resource management.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black-owned",
    phoneNumber: "",
    searchTags: "Wright, Best, consulting, leadership, training",
    subCategory: "Consulting",
    image: ""
  },
  {
    name: "Bed of Nails",
    address: "2272 Adam Clayton Powell Jr.",
    city: "New York,",
    state: "NY",
    zip: 10030,
    website: "http://www.bedofnailsnyc.com/",
    category: "Beauty",
    description: "At Bed of Nails, we offer the most unique and luxurious grooming experience for men and women. Owner and celebrity manicurist, Candice Idehen, made sure her salon not only provides an inviting, modern interior and designer products that push beyond industry standards, but also makes the perfect date, girls night out, bridal party or event destination.",
    giveBack: "",
    hireLocal: "",
    meetCriteria: "",
    owner: "Black woman-owned",
    phoneNumber: "(212) 694-2200",
    searchTags: "Bed, of, Nails, Beauty, Nail, Manicure, pedicure",
    subCategory: "Nail Salon",
    image: ""
  }
]


function seedDB(){
    //Remove all businesses
    Business.remove({}, function(err){
    if(err){
        console.log(err);
    }
    console.log("removed businesss");
     //add a few businesses
    data.forEach(function(seed){
        Business.create(seed, function(err, data){
            if(err){
                console.log(err)
            } else{
                console.log("added a business");
            }
        });
    });
    });
   
    
    
    //add a few reviews
}

module.exports = seedDB;